#!/bin/sh
basedir=$(dirname $0)

. ${basedir}/../../release_versioning

crayversion=
branch=
if [ ! -z ${build_number} ]; then
 # This version was built from a non-release branch
  crayversion="${major:-0}.${minor:-0}.${revision}.${build_number}"
  branch="master"
else
  # This version was built from a release branch
  crayversion="${major:-0}.${minor:-0}.${revision}"
  branch="release"
fi

cdstsupportversionmin=$(echo ${CRAY_CDST_SUPPORT_VERSION} | awk -F . '{ print $1"."$2 }')
tmpver=$(echo ${CRAY_CDST_SUPPORT_VERSION} | awk -F . '{ print $1 }')
cdstsupportversionmax=$(($tmpver+1))

ctiversionmin=$(echo ${CTI_VERSION} | awk -F . '{ print $1"."$2 }')
tmpver=$(echo ${CTI_VERSION} | awk -F . '{ print $1 }')
ctiversionmax=$(($tmpver+1))

arguments=$(getopt -o csmtx --long crayversion,cdstversionmin,cdstversionmax,ctiversionmin,ctiversionmax,branch -n ${0} -- "$@")

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

while true ; do
    case "$1" in
        -c|--crayversion) echo "${crayversion}" ; shift ;;
        -s|--cdstversionmin) echo "${cdstsupportversionmin}" ; shift ;;
        -m|--cdstversionmax) echo "${cdstsupportversionmax}" ; shift ;;
        -t|--ctiversionmin) echo "${ctiversionmin}" ; shift ;;
        -x|--ctiversionmax) echo "${ctiversionmax}" ; shift ;;
        -b|--branch) echo "${branch}" ; shift ;;
        *) break ;;
    esac
done
