#!/bin/bash

# Builder: You must edit this script to define:
#    product_name= product name as it appears in /opti, /opt/cray, 
#    or /opt/cray/pe.
#    version_string= version being installed
#    install_dir= either /opt, /opt/cray, or /opt/cray/pe
#    module_dir= either /opt/modulefiles, /opt/cray/modulefiles, or 
#    /opt/cray/pe/modulefiles
#    mod_names= list of names of modulefiles for this install
#    i.e. ="cray-mpich cray-shmem"
#
#    Save this file in /opt/cray/2.4.0 as  
#    set_default_craype_2.4.0
#    You can invoke your finished script with "--help" or with 
#    "-cray_links_only"

export CRAY_product=[product_name]
export CRAY_version=[version_string]
export CRAY_inst_dir=[install_dir]
export CRAY_mod_dir=[module_dir]
export CRAY_mod_names=[module_name_list]
export CRAY_lmod_dirs=[lmod_dir_list]
export CRAY_lmod_names=[lmod_name_list]

if [ -e /opt/cray/pe/bin/set_default_master ] ; then
  /opt/cray/pe/bin/set_default_master "$@"
else
  echo "The set_default script is not installed in /opt/cray/pe/bin."
  echo "The 'cray-pe-set-default' package must be installed."
  exit 1
fi
